name: Release package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Make a Release using release-it
      - name: Make a Release
        if: startsWith(github.event.inputs.release-type, 'major') == true
        run: npm run release

      - name: Make a Release
        if: startsWith(github.event.inputs.release-type, 'minor') == true
        run: npm run release:minor